### ISSUE TITLE
Create "Badge Creation" Page 1

### ISSUE THREAD

**Issue by kellgolden** [FightPandemics/FightPandemics-web3-badges#11]
**User Story**

As a Logged-in FP Coordinator user, as I look through the Create Badge tab, I should be prompt to do the following:

- ***Input the title of the badge***
- ***Description of the badge***
- ***Tags - for the badge***
- ***Quantity of badges***
- ***Upload the image of the badge icon or remove the uploaded image***

<img width="462" alt="Screen Shot 2021-02-18 at 8 47 10 PM" src="https://user-images.githubusercontent.com/64812703/108445490-7c07a200-722a-11eb-80e4-bc44484e1644.png">

<img width="422" alt="Screen Shot 2021-02-18 at 8 47 35 PM" src="https://user-images.githubusercontent.com/64812703/108445522-8a55be00-722a-11eb-9d48-f89c4f604478.png">

After I've inputted the necessary information for the badge, I should be able to "**Create Badge".**

<img width="418" alt="Screen Shot 2021-02-18 at 8 47 53 PM" src="https://user-images.githubusercontent.com/64812703/108445549-95a8e980-722a-11eb-86f8-16cc02e9ef63.png">

- Once I create a badge, I should be notified that the badge created successfully.
- After the badge is created successfully, I should be prompt to do the following:
    - Assign Badge 
    - Close

**Link to Designs:** https://www.figma.com/file/EMKcg0eTnOlr7bRZGFdnZu/Web-app-product-spec?node-id=790%3A25

**Link to feature requirements:** https://www.notion.so/fightpandemics/Mint-Badges-Bounty-Project-3a345fa59d1541609266cb0ecf903f8e

**Acceptance Criteria**

Can the logged-in user do the following: 

- ***Input the title of the badge***
- ***Description of the badge***
- ***Tags - for the badge***
- ***Quantity of badges***
- ***Upload the image of the badge icon or remove the uploaded image***
- ***Create a badge*** as a result of adding the above items

**Comment by mushfichowdhury** [comment]
PR approved
